-- Baseline schema for the Voltio core banking database (PostgreSQL).
--
-- Authored from the 16 @Entity classes under com.group1.banking.entity, and
-- audited on every startup by spring.jpa.hibernate.ddl-auto=validate: any
-- mismatch between this file and an entity mapping fails the boot and names
-- the offending table or column.
--
-- Supersedes the pre-Postgres scripts V001__create_savings_goals.sql,
-- V002__account_control_freeze_unfreeze.sql and V003__create_audit_log.sql,
-- which were H2/MySQL dialect and were never applied by Flyway.

-- ---------------------------------------------------------------------------
-- Customers, accounts, transactions
-- ---------------------------------------------------------------------------

CREATE TABLE customers (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    address         VARCHAR(255) NOT NULL,
    type            INTEGER NOT NULL,
    date_of_birth   DATE NOT NULL,
    kyc_verified    BOOLEAN NOT NULL,
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- account_id is assigned by the application, not generated by the database
-- (Account has @Id with no @GeneratedValue).
CREATE TABLE account (
    account_id           BIGINT PRIMARY KEY,
    customer_id          BIGINT NOT NULL,
    account_type         VARCHAR(255) NOT NULL,
    status               VARCHAR(255) NOT NULL,
    balance              NUMERIC(19, 2) NOT NULL,
    interest_rate        NUMERIC(12, 4),
    account_number       VARCHAR(255) NOT NULL,
    daily_transfer_limit NUMERIC(19, 2) NOT NULL,
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    closed_at            TIMESTAMP(6) WITH TIME ZONE,
    version              BIGINT NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE bank_transaction (
    transaction_id          VARCHAR(255) PRIMARY KEY,
    account_id              BIGINT NOT NULL,
    amount                  NUMERIC(19, 2) NOT NULL,
    direction               VARCHAR(255) NOT NULL,
    status                  VARCHAR(255) NOT NULL,
    timestamp               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    description             VARCHAR(255),
    sender_info             VARCHAR(100),
    receiver_info           VARCHAR(100),
    idempotency_key         VARCHAR(255),
    category                VARCHAR(50),
    external_transaction_id VARCHAR(36) UNIQUE,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account (account_id)
);

-- ---------------------------------------------------------------------------
-- Identity and access
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    user_id             UUID PRIMARY KEY,
    username            VARCHAR(255) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    external_subject_id VARCHAR(255),
    customer_id         BIGINT,
    is_active           BOOLEAN NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE
);

-- @ElementCollection collection table for User.roles.
CREATE TABLE user_roles (
    user_id   UUID NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE roles (
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    permissions VARCHAR(2000)
);

-- ---------------------------------------------------------------------------
-- Savings goals
-- ---------------------------------------------------------------------------

CREATE TABLE savings_goals (
    goal_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT NOT NULL,
    account_id    BIGINT NOT NULL,
    goal_name     VARCHAR(255) NOT NULL,
    target_amount NUMERIC(19, 2) NOT NULL,
    target_date   DATE NOT NULL,
    status        VARCHAR(255) NOT NULL,
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_sg_customer_account UNIQUE (customer_id, account_id),
    CONSTRAINT fk_savings_goal_account FOREIGN KEY (account_id) REFERENCES account (account_id)
);

CREATE INDEX idx_sg_customer_id ON savings_goals (customer_id);
CREATE INDEX idx_sg_account_id ON savings_goals (account_id);
CREATE INDEX idx_sg_status ON savings_goals (status);

-- ---------------------------------------------------------------------------
-- GICs
-- ---------------------------------------------------------------------------

CREATE TABLE gic_investment (
    gic_id           VARCHAR(255) PRIMARY KEY,
    account_id       BIGINT NOT NULL,
    principal_amount NUMERIC(19, 2) NOT NULL,
    interest_rate    NUMERIC(12, 4) NOT NULL,
    term             VARCHAR(255) NOT NULL,
    start_date       DATE NOT NULL,
    maturity_date    DATE NOT NULL,
    maturity_amount  NUMERIC(19, 2) NOT NULL,
    status           VARCHAR(255) NOT NULL,
    deleted_at       TIMESTAMP(6) WITH TIME ZONE,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_gic_account FOREIGN KEY (account_id) REFERENCES account (account_id)
);

-- ---------------------------------------------------------------------------
-- Risk scoring
-- ---------------------------------------------------------------------------

-- RiskScore declares @Column(name = "calculatedAt"). Spring Boot's default
-- physical naming strategy (CamelCaseToUnderscoresNamingStrategy) rewrites
-- camelCase to snake_case even for an explicitly-named column, so Hibernate
-- looks for calculated_at, not calculatedat.
CREATE TABLE risk_scores (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version DOUBLE PRECISION,
    score        DOUBLE PRECISION,
    band         VARCHAR(255),
    status       VARCHAR(255),
    factors      VARCHAR(2000),
    calculated_at TIMESTAMP(6) WITH TIME ZONE,
    customer_id  BIGINT NOT NULL,
    CONSTRAINT fk_risk_score_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE INDEX idx_customer_score_created ON risk_scores (customer_id, calculated_at);

-- ---------------------------------------------------------------------------
-- Standing orders
-- ---------------------------------------------------------------------------

CREATE TABLE standing_orders (
    standing_order_id VARCHAR(36) PRIMARY KEY,
    source_account_id BIGINT NOT NULL,
    payee_account     BIGINT NOT NULL,
    payee_name        VARCHAR(70) NOT NULL,
    amount            NUMERIC(19, 2) NOT NULL,
    frequency         VARCHAR(20) NOT NULL,
    start_date        TIMESTAMP(6) NOT NULL,
    end_date          TIMESTAMP(6),
    reference         VARCHAR(18) NOT NULL,
    status            VARCHAR(30) NOT NULL,
    next_run_date     TIMESTAMP(6) NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_so_source_account_id ON standing_orders (source_account_id);
CREATE INDEX idx_so_status ON standing_orders (status);
CREATE INDEX idx_so_next_run_date ON standing_orders (next_run_date);

-- ---------------------------------------------------------------------------
-- Agent confirmation gate
-- ---------------------------------------------------------------------------

CREATE TABLE pending_agent_actions (
    token           VARCHAR(36) PRIMARY KEY,
    customer_id     BIGINT NOT NULL,
    action_type     VARCHAR(20) NOT NULL,
    parameters_json TEXT NOT NULL,
    human_summary   TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_paa_customer_id ON pending_agent_actions (customer_id);
CREATE INDEX idx_paa_status ON pending_agent_actions (status);

-- ---------------------------------------------------------------------------
-- Statement export cache
-- ---------------------------------------------------------------------------

-- pdf_data is BYTEA here. ExportCacheEntity currently declares
-- columnDefinition = "LONGBLOB", which is MySQL-only and has no PostgreSQL
-- equivalent; that annotation must be changed for this table to validate.
CREATE TABLE export_cache (
    cache_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    param_hash VARCHAR(64) NOT NULL,
    pdf_data   BYTEA NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_ec_account_param_hash UNIQUE (account_id, param_hash)
);

-- ---------------------------------------------------------------------------
-- Idempotency
-- ---------------------------------------------------------------------------

-- response_body is TEXT here. IdempotencyRecord declares a bare @Lob on a
-- String, which Hibernate maps to a PostgreSQL large object (oid) rather than
-- text; that annotation must be adjusted for this table to validate.
CREATE TABLE idempotency_record (
    storage_key     VARCHAR(320) PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    caller_user_id  VARCHAR(64) NOT NULL,
    operation_type  VARCHAR(50) NOT NULL,
    response_status INTEGER NOT NULL,
    response_body   TEXT NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------

CREATE TABLE notification_decisions (
    event_id           VARCHAR(36) PRIMARY KEY,
    event_type         VARCHAR(100) NOT NULL,
    account_id         BIGINT NOT NULL,
    customer_id        BIGINT NOT NULL,
    business_timestamp TIMESTAMP(6) NOT NULL,
    payload            TEXT,
    decision           VARCHAR(20) NOT NULL,
    decision_reason    VARCHAR(500) NOT NULL,
    mandatory_override BOOLEAN NOT NULL,
    evaluated_at       TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_nd_account_id ON notification_decisions (account_id);
CREATE INDEX idx_nd_customer_id ON notification_decisions (customer_id);
CREATE INDEX idx_nd_event_type ON notification_decisions (event_type);

CREATE TABLE notification_preferences (
    preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT NOT NULL,
    event_type    VARCHAR(100) NOT NULL,
    opted_in      BOOLEAN NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_np_customer_event UNIQUE (customer_id, event_type)
);

CREATE INDEX idx_np_customer_id ON notification_preferences (customer_id);

-- ---------------------------------------------------------------------------
-- Account control (freeze / unfreeze)
-- ---------------------------------------------------------------------------

CREATE TABLE account_control_audit (
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT NOT NULL,
    admin_user_id   VARCHAR(80) NOT NULL,
    admin_role      VARCHAR(50) NOT NULL,
    action_type     VARCHAR(20) NOT NULL,
    previous_status VARCHAR(20) NOT NULL,
    new_status      VARCHAR(20) NOT NULL,
    reason          VARCHAR(500) NOT NULL,
    notes           VARCHAR(1000),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_aca_account ON account_control_audit (account_id);
CREATE INDEX idx_aca_created_at ON account_control_audit (created_at);

-- ---------------------------------------------------------------------------
-- Shared audit log
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    log_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(60) NOT NULL,
    source_feature VARCHAR(100),
    actor_type     VARCHAR(50) NOT NULL,
    actor_id       VARCHAR(50) NOT NULL,
    subject_type   VARCHAR(60) NOT NULL,
    subject_id     VARCHAR(100),
    outcome        VARCHAR(20) NOT NULL,
    event_details  TEXT,
    timestamp      TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_al_actor_id ON audit_log (actor_id);
CREATE INDEX idx_al_subject ON audit_log (subject_type, subject_id);
CREATE INDEX idx_al_timestamp ON audit_log (timestamp);
